DATA:
  IMG_SIZE: 224
MODEL:
  TYPE: swin
  NAME: swin_base_patch4_window7_224
  NUM_CLASSES: 6
  SWIN:
    PATCH_SIZE: 4
    IN_CHANS: 3
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    WINDOW_SIZE: 7
