DATA:
  IMG_SIZE: 224
MODEL:
  TYPE: swin
  NAME: swin_tiny_patch4_window7_224
  DROP_PATH_RATE: 0.1
  NUM_CLASSES: 2
  SWIN:
    EMBED_DIM: 96
    IN_CHANS: 3
    PATCH_SIZE: 4
    DEPTHS: [ 2, 2, 6, 2 ]
    NUM_HEADS: [ 3, 6, 12, 24 ]
    WINDOW_SIZE: 7